### ISSUE TITLE
The `Vsix` generated class name collides with the `Microsoft.VisualStudio.ExtensionManager.Vsix` class.

### ISSUE THREAD

**Issue by astrohart** [madskristensen/VsixSynchronizer#12]
@madskristensen  When I have a `VsPackage`, say:

```C#
// The first few lines of VsPackage.cs in the ExtensionPackTools extension
namespace ExtensionManager
{
    [PackageRegistration(UseManagedResourcesOnly = true, AllowsBackgroundLoading = true)]
    [InstalledProductRegistration(Vsix.Name, Vsix.Description, Vsix.Version)]
    [ProvideMenuResource("Menus.ctmenu", 1)]
    [Guid(PackageGuids.guidVsPackageString)]
    [ProvideAutoLoad(VSConstants.UICONTEXT.SolutionOpening_string, PackageAutoLoadFlags.BackgroundLoad)]
    public sealed class VsPackage : AsyncPackage
    {
        protected override async Task InitializeAsync(CancellationToken cancellationToken, IProgress<ServiceProgressData> progress)
        {
             /* ... */
        }

       /* ... */
    }
}
```
and in the attributes, it references the `Vsix` class produced by this extension, but if I change the namespace (for whatever reason), say, to `Foo` so that the namespaces are no longer in sync, then it collides with the `Microsoft.VisualStudio.ExtensionManager.Vsix` class:

![image](https://user-images.githubusercontent.com/8261875/150433212-e0fa5b38-538d-40cd-ba68-6278bbcf6690.png)

Am not saying this is going to happen often but it would be a good idea to disambiguate this.  I propose altering the code in the `VsixManifestGenerator.cs` file to generate a class named `VsixMetadata` or `VsixAttributes` and then there will be less of a chance of name collision.

**Comment by astrohart** [comment]
I should note that the `Microsoft.VisualStudio.ExtensionManager.Vsix` class is documented; this took me completely by surprise as I was fiddle-faddling with the code on my own branch earlier.  But I strongly recommend disambiguation so as to avoid conflicts with Microsoft entities.

**Comment by astrohart** [comment]
I suggest going with `VsixAttributes` because `VsixManifest` is already a name of a class in this project, so we do not want name collisions happening during CI/CD.

**Comment by astrohart** [comment]
@madskristensen please see PR #13

**Comment by madskristensen** [comment]
Microsoft.VisualStudio.ExtensionManager isn't part of the VSSDK

**Comment by astrohart** [comment]
Well, look for yourself @madskristensen on the screen capture in the issue post.  The `Vsix` class is green when it should not be (I changed the namespace to `Foo` on purpose (then changed it back after taking the screen capture) in order to get it to not see the `Vsix` class generated by the **VSIX Synchronizer** extension.   And lo and behold it's still green (and notice there is a ToolTip showing the fully-qualified name of the class.

It must be being defined by one of the NuGet packages in the solution.

This is after a fresh clone, so it's not a change I made (at least, since getting PRs merged).  You can see from my previous PRs I have not altered the NuGet packages (save for the most recent one where I simply removed unused/unneeded references, but this was done mostly when I had just done Add > New Project in Solution Explorer to try and cut down on system resources ar run time).

**Comment by madskristensen** [comment]
That's because the ExtensionPackTools uses an unsupported API by referencing the private .dll directly. This is a problem only that extension faces and it's been with it so far with no issues.

**Comment by astrohart** [comment]
OK! Then I stand corrected, this is not an issue so long as we don't change the namespace to `Foo`.
